name: CI > Rollout k8s status

# Controls when the action will run.
on:
  # Triggers the workflow
  schedule:
    - cron: "*/60 * * * *" # 5:00AM UTC +8

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rollout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      DEPLOYMENT: webserver-depl

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # configure kubectl
      - uses: tale/kubectl-action@v1
        with:
          # For this method KUBE_CONFIG required.
          # You can find it: cat $HOME/.kube/config | base64
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          run: |
            kubectl get pods
            kubectl rollout status deployment/$DEPLOYMENT
